### ISSUE TITLE
Incorrect parameter names and docstrings

### ISSUE THREAD

**Issue by hex-yes** [adafruit/Adafruit_CircuitPython_RA8875#15]
First, the RA8875 driver board and library helped me complete my project, and I sincerely appreciate the effort that went into both.

I discovered that the parameter names for the `_rect_helper` method of the `RA8875` class are inconsistent with the actual drawing behavior. The method signature is:

`_rect_helper(self, x, y, width, height, color, filled)`

However, the `width` and `height` parameters should really be the x- and y-coordinate of the endpoint--they are a second absolute x-y screen coordinate, rather than a width and height offset applied to the first screen coordinate. Page 120 of the [RA8875 datasheet](https://cdn-shop.adafruit.com/datasheets/RA8875_DS_V19_Eng.pdf) that is linked from the Adafruit product page confirms the registers written by this method are an endpoint coordinate, not width/height.

This parameter mislabeling carries through to the public methods of the same class that rely on the `_rect_helper` method, including at least the `rect` and `fill_rect` methods (but possibly others...these are just the ones I happened to use with confusing results).

I would suggest that the signature of the `_rect_helper` method be changed to be consistent with other methods like `_triangle_helper`:

`_rect_helper(self, x1, y1, x2, y2, color, filled)`

I would then suggest that the parameters and documentation for other methods like `rect` and `fill_rect` that currently specify a width/height be updated accordingly. By changing the parameter names and documentation, existing code (including the examples) that relies on the existing behavior will not be broken.

**Comment by makermelissa** [comment]
Good catch. Yeah, I think I based it off the Arduino driver, but taking a closer look at that, that takes the x and y offset into account. I'll update it to behave as the Arduino driver does and just release as a version 3.0.0, because it may break code.

**Comment by hex-yes** [comment]
In the Arduino driver, it looks like (and check me on this) that the `rectHelper` method has mislabeled parameters. It does not actually take a width and height, but instead takes the endpoint coordinate. However, in the Arduino driver, this is compensated for by all the methods that call `rectHelper` adding the passed width and height to the x-y start point coordinate, so it doesn't cause any public-facing grief.

**Comment by makermelissa** [comment]
That sounds correct.

**Comment by hex-yes** [comment]
With that in mind, if you update all the calls to `_rect_helper` in the Python driver like so:

`self._rect_helper(x, y, width, height, color, False)`
to
`self._rect_helper(x, y, x+width, y+height, color, False)`

It should then work like the Arduino driver (with the same mislabeled params in the helper method, but compensated for in the public-facing methods). The example code in the Python driver would also need to be updated for the new behavior.

**Comment by makermelissa** [comment]
I'm updating them to:
`self._rect_helper(x, y, x + width - 1, y + height - 1, color, False)`

**Comment by hex-yes** [comment]
Ah, right you are. Thanks!
